name: Packagist heartbeat

on:
  schedule:
    - cron:  '1/13 4-10 * * *'
  workflow_dispatch:

jobs:
   package-test:
    name: "Composer package install test"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - '8.1'
    steps:
      - name: Install dependencies
        run: composer require ouxsoft/luckbydice
